import { LegosMetadata, categoryIds } from "./declarations";

export const legosMetadata: LegosMetadata[] = [
  {
    id: "ai-01",
    category: categoryIds.AI,
    name: "AI Chat with Voice Input",
    description: "Modern AI chat interface with voice input, file attachments, and expandable textarea",
    iframeHeight: "450px",
    type: "file",
  },
  {
    id: "ai-02",
    category: categoryIds.AI,
    name: "AI Chat with Model Selection",
    description: "AI chat interface with model selector, prompt suggestions, and image attachments",
    iframeHeight: "400px",
    type: "file",
  },
  {
    id: "ai-03",
    category: categoryIds.AI,
    name: "AI Chat Compact Interface",
    description: "Compact AI chat with model, agent, and performance mode selectors",
    iframeHeight: "350px",
    type: "file",
  },
  {
    id: "ai-04",
    category: categoryIds.AI,
    name: "AI Chat with File Attachments",
    description: "Full-featured AI chat with drag & drop file attachments, settings, and action buttons",
    iframeHeight: "650px",
    type: "file",
  },
  {
    id: "ai-05",
    category: categoryIds.AI,
    name: "AI Input with Model Selector",
    description: "Modern AI input textarea with model dropdown featuring Claude and OpenAI icons",
    iframeHeight: "400px",
    type: "file",
  },
  {
    id: "flow-01",
    category: categoryIds.Flow,
    name: "Flight Card White",
    description: "Clean white flight card with image, pricing, and like button",
    iframeHeight: "700px",
    type: "file",
  },
  {
    id: "flow-02",
    category: categoryIds.Flow,
    name: "Flight Card Overlay",
    description: "Stunning flight card with full-bleed background and glassmorphism effects",
    iframeHeight: "700px",
    type: "file",
  },
  {
    id: "grid-01",
    category: categoryIds.Grids,
    name: "Dark Infrastructure Bento",
    description: "Minimal dark bento grid with analytics, stats, and feature cards",
    iframeHeight: "900px",
    type: "file",
  },
  {
    id: "grid-02",
    category: categoryIds.Grids,
    name: "Glassmorphism Workspace",
    description: "Light glassmorphism bento with integrations, stats, and quick actions",
    iframeHeight: "800px",
    type: "file",
  },
  {
    id: "grid-03",
    category: categoryIds.Grids,
    name: "Brutalist Agency",
    description: "Bold brutalist bento with typography, projects, and audio player",
    iframeHeight: "900px",
    type: "file",
  },
  {
    id: "grid-04",
    category: categoryIds.Grids,
    name: "Neomorphic Dashboard",
    description: "Soft neomorphic bento with system metrics and device monitoring",
    iframeHeight: "850px",
    type: "file",
  },
  {
    id: "grid-05",
    category: categoryIds.Grids,
    name: "Social Creator",
    description: "Dark social/creative bento with posts, engagement, and trending tags",
    iframeHeight: "850px",
    type: "file",
  },
  {
    id: "versatile-01",
    category: categoryIds.Versatile,
    name: "Animated Testimonials",
    description: "Stacked image testimonials with autoplay, smooth animations, and navigation controls",
    iframeHeight: "600px",
    type: "file",
  },
  {
    id: "versatile-02",
    category: categoryIds.Versatile,
    name: "Card Stack",
    description: "Animated card stack with progress indicator, autoplay, and vertical navigation",
    iframeHeight: "500px",
    type: "file",
  },
];
